[rewrite_local]
^https?:\/\/mobile\.flightradar24\.com\/mobile\/(user-session|\w{9}) url script-echo-response https://raw.githubusercontent.com/Benjam1nF/ProxyRes/refs/heads/main/Misc/M/Fr24/Fr24.js

[mitm] 
hostname = mobile.flightradar24.com
